#' Synthetic polygons for H3 workflow testing
#'
#' A deterministic `sf` dataset containing synthetic polygon geometries used
#' in examples, tests, and demonstrations of H3 coverage and compaction
#' workflows.
#'
#' The geometries represent several polygon forms relevant to spatial
#' coverage testing: a regular polygon, an irregular polygon, a more complex
#' polygon, and a polygon containing an interior hole.
#'
#' @format An `sf` object with 4 rows and 2 columns:
#' \describe{
#'   \item{geometry_id}{Character identifier for the synthetic geometry.}
#'   \item{geometry}{Polygon geometry in EPSG:4326.}
#' }
#'
#' @source Synthetic data generated by `h3compactR`.
#'
#' @examples
#' toy_polygons
#'
#' @keywords datasets
"toy_polygons"

#' Synthetic polygons for H3 membership and assignment testing
#'
#' A deterministic `sf` dataset containing synthetic polygon geometries used
#' in examples, tests, and demonstrations of H3 polygon membership and
#' assignment workflows.
#'
#' The dataset includes adjacent polygons, a polygon containing an interior
#' hole, a polygon occupying that hole, and a multipart polygon. The features
#' are constructed without positive-area interior overlap.
#'
#' @format An `sf` object with 5 rows and 2 columns:
#' \describe{
#'   \item{feature_id}{Character identifier for the synthetic polygon feature.}
#'   \item{geometry}{Polygon or multipolygon geometry in EPSG:4326.}
#' }
#'
#' @source Synthetic data generated by `h3compactR`.
#'
#' @examples
#' toy_membership_polygons
#'
#' @keywords datasets
"toy_membership_polygons"