#' Synthetic polygons for H3 workflow testing
#'
#' A deterministic `sf` dataset containing synthetic polygon geometries used
#' in examples, tests, and demonstrations of H3 coverage and compaction
#' workflows.
#'
#' The geometries represent several polygon forms relevant to spatial
#' coverage testing: a regular polygon, an irregular polygon, a more complex
#' polygon, and a polygon containing an interior hole.
#'
#' @format An `sf` object with 4 rows and 2 columns:
#' \describe{
#'   \item{geometry_id}{Character identifier for the synthetic geometry.}
#'   \item{geometry}{Polygon geometry in EPSG:4326.}
#' }
#'
#' @source Synthetic data generated by `h3compactR`.
#'
#' @examples
#' toy_polygons
#'
#' @keywords datasets
"toy_polygons"


#' Synthetic polygon geography for membership and assignment examples
#'
#' A deterministic `sf` dataset containing five synthetic polygon features
#' designed to exercise polygon membership and exclusive H3 assignment. The
#' geography includes adjacent polygons with a shared boundary, a polygon with
#' an interior hole, a separate polygon occupying that hole, and a multipart
#' polygon. Feature interiors do not overlap.
#'
#' @format An `sf` object with 5 rows and 2 columns:
#' \describe{
#'   \item{feature_id}{Character identifier for the synthetic feature.}
#'   \item{geometry}{Polygon or multipolygon geometry in EPSG:4326.}
#' }
#'
#' @source Synthetic data generated by `h3compactR`.
#'
#' @examples
#' toy_membership_polygons
#'
#' @keywords datasets
"toy_membership_polygons"
