#' Synthetic polygons for H3 workflow testing
#'
#' A deterministic `sf` dataset containing synthetic polygon geometries used
#' in examples, tests, and demonstrations of H3 coverage and compaction
#' workflows.
#'
#' The geometries represent several polygon forms relevant to spatial
#' coverage testing: a regular polygon, an irregular polygon, a more complex
#' polygon, and a polygon containing an interior hole.
#'
#' @format An `sf` object with 4 rows and 2 columns:
#' \describe{
#'   \item{geometry_id}{Character identifier for the synthetic geometry.}
#'   \item{geometry}{Polygon geometry in EPSG:4326.}
#' }
#'
#' @source Synthetic data generated by `h3compactR`.
#'
#' @examples
#' toy_polygons
#'
#' @keywords datasets
"toy_polygons"
